// const text = document.querySelector('button');
// text.textContent = 'goodbye';
// const img = document.getElementById('myImage');
// img.setAttribute("src", "two.png");
// const link = document.getElementById('link');
// link.setAttribute("href", "https://youtu.be/NaZeslUINF4?feature=shared");
// const img2 = document.getElementById("src");
// img2.setAttribute("alt", "new alt");
// const uli = document.getElementById('ul');
// const first = uli.querySelector('li');
// first.textContent = "привіт";
const text = document.createElement('h1');
console.log(text);